/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kristian' at '25.09.16 11:37' with Gradle 2.2.1
 *
 * @author Kristian, @date 25.09.16 11:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
